import {useEffect,useState,useRef} from 'react'
import type {RefObject} from 'react'
import type {Context} from '@deepseek-ai/cordis'
import type {AppRecipe} from './recipe-api.ts'
import {captureAnnotation,annotationText} from './annotation.ts'
import type {CanvasAnnotation} from './annotation.ts'
import type {} from './annotation-client.ts'
export function AnnotationLayer({canvas,recipe,pageId,instanceId,ctx,active,t}:{canvas:RefObject<HTMLDivElement>;recipe:AppRecipe;pageId:string;instanceId:string;ctx?:Context;active:boolean;t:(key:any)=>string}){
 const [aiming,setAiming]=useState(false),[selection,setSelection]=useState<CanvasAnnotation|null>(null),[requirement,setRequirement]=useState(''),[roleId,setRole]=useState(''),[marks,setMarks]=useState<CanvasAnnotation[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),start=useRef<{x:number;y:number}>(), pending=useRef<AbortController>(),[dragBox,setDragBox]=useState<CanvasAnnotation['box']|null>(null)
 const identity=JSON.stringify([recipe.appId,instanceId,pageId,recipe.version]),identityRef=useRef(identity);identityRef.current=identity
 useEffect(()=>{if(!active){pending.current?.abort();setBusy(false);setAiming(false);setSelection(null);setDragBox(null)}},[active])
 useEffect(()=>{if(!aiming&&!selection)return;const cancel=(event:KeyboardEvent)=>{if(event.key==='Escape'){pending.current?.abort();setBusy(false);setAiming(false);setSelection(null);setDragBox(null)}};window.addEventListener('keydown',cancel);return()=>window.removeEventListener('keydown',cancel)},[aiming,selection])
 useEffect(()=>{const scroll=canvas.current?.querySelector('.pwb-recipe-page');const clear=()=>setMarks([]);scroll?.addEventListener('scroll',clear);return()=>scroll?.removeEventListener('scroll',clear)},[canvas,identity])
 useEffect(()=>{setBusy(false);setAiming(false);setSelection(null);setMarks([]);setRequirement('');setError('');setNotice('');setDragBox(null);return()=>pending.current?.abort()},[identity])
 const page=recipe.pages.find(page=>page.id===pageId);if(!page)return null
 const confirm=async()=>{if(!selection||!roleId)return;const captured=identity;const controller=new AbortController();pending.current=controller;setBusy(true);setError('');try{
  if(!recipe.roles.some(role=>role.id===roleId)||selection.moduleId&&!page.modules.some(module=>module.id===selection.moduleId))throw Error(t('annotationTargetChanged'))
  const bridge=ctx?.get('personalWorkbenchAnnotations');if(!bridge)throw Error(t('annotationUnavailable'))
  await bridge.append({appId:recipe.appId,instanceId,roleId},annotationText(recipe,instanceId,pageId,selection,requirement),controller.signal)
  if(identityRef.current===captured){setMarks(old=>[...old,selection].slice(-20));setSelection(null);setRequirement('');setNotice(t('annotationAdded'))}
 }catch(error){if(identityRef.current===captured)setError(error instanceof Error?error.message:String(error))}finally{if(identityRef.current===captured)setBusy(false)}}
 return <><style>{annotationStyles}</style><div className="pwb-annotation-toolbar" data-pwb-annotation-ui><button data-pwb-button type="button" aria-pressed={aiming} disabled={busy} onClick={()=>{setAiming(!aiming);setSelection(null);setError('');setNotice('')}}>{t(aiming?'annotationCancel':'annotationStart')}</button>{aiming&&<small>{t('annotationHint')}</small>}{notice&&<span role="status">{notice}</span>}</div>
 {active&&marks.map((mark,index)=><span key={mark.id} className="pwb-annotation-mark" aria-label={t('annotationMark')+' '+(index+1)} style={{left:mark.box.x,top:mark.box.y,width:Math.max(mark.box.width,18),height:Math.max(mark.box.height,18)}}>{index+1}</span>)}
 {active&&aiming&&<div className="pwb-annotation-aim" role="region" aria-label={t('annotationArea')} onPointerDown={event=>{if(event.button!==0)return;start.current={x:event.clientX,y:event.clientY};event.currentTarget.setPointerCapture?.(event.pointerId)}} onPointerUp={event=>{if(!start.current||!canvas.current)return;const capture=captureAnnotation(canvas.current,start.current,{x:event.clientX,y:event.clientY},page);start.current=undefined;setDragBox(null);setSelection(capture);setRole(page.modules.find(module=>module.id===capture.moduleId)?.roleId??'');setAiming(false)}} onPointerMove={event=>{if(!start.current||!canvas.current)return;const r=canvas.current.getBoundingClientRect();setDragBox({x:Math.max(0,Math.min(start.current.x,event.clientX)-r.left),y:Math.max(44,Math.min(start.current.y,event.clientY)-r.top),width:Math.abs(event.clientX-start.current.x),height:Math.abs(event.clientY-start.current.y)})}} onPointerCancel={()=>{start.current=undefined;setDragBox(null);setAiming(false)}} onKeyDown={event=>{if(event.key==='Escape')setAiming(false)}} tabIndex={0}/>}
 {active&&(dragBox??selection?.box)&&<span className="pwb-annotation-mark" aria-hidden="true" style={{left:(dragBox??selection!.box).x,top:(dragBox??selection!.box).y,width:Math.max((dragBox??selection!.box).width,18),height:Math.max((dragBox??selection!.box).height,18)}}/>}
 {active&&selection&&<section className="pwb-annotation-editor" data-pwb-annotation-ui aria-label={t('annotationEditor')}><strong>{selection.moduleTitle}</strong><small>{t('annotationPosition')}: {Math.round(selection.box.x)}, {Math.round(selection.box.y)} · {Math.round(selection.box.width)} × {Math.round(selection.box.height)}</small>{selection.limited&&<p role="status">{t('annotationLimited')}</p>}{selection.text&&<details><summary>{t('annotationContext')}</summary><pre>{selection.text}</pre></details>}<label>{t('annotationRequirement')}<textarea aria-label={t('annotationRequirement')} rows={3} maxLength={2000} value={requirement} disabled={busy} onChange={event=>setRequirement(event.target.value)}/></label><label>{t('annotationRole')}<select aria-label={t('annotationRole')} value={roleId} disabled={busy} onChange={event=>setRole(event.target.value)}><option value="">{t('annotationChooseRole')}</option>{recipe.roles.map(role=><option key={role.id} value={role.id}>{role.name}</option>)}</select></label><div><button data-pwb-button data-variant="primary" type="button" disabled={busy||!roleId||!requirement.trim()} onClick={()=>{void confirm()}}>{t('annotationAppend')}</button><button data-pwb-button type="button" disabled={busy} onClick={()=>{setSelection(null);setError('')}}>{t('annotationCancel')}</button></div><small>{t('annotationNoSend')}</small>{error&&<p role="alert">{error}</p>}</section>}
 </>
}
const annotationStyles=' .pwb-annotation-toolbar{position:relative;z-index:10;height:44px;flex-shrink:0;display:flex;align-items:center;gap:10px;padding:4px 16px;box-sizing:border-box}.pwb-annotation-toolbar small,.pwb-annotation-toolbar span{font-size:12px;color:var(--pwb-muted)}.pwb-annotation-aim{position:absolute;inset:44px 0 0;z-index:20;cursor:crosshair;background:#7096b60b;touch-action:none}.pwb-annotation-mark{position:absolute;z-index:15;pointer-events:none;box-sizing:border-box;border:2px solid var(--pwb-accent,#b36b4e);border-radius:4px;color:var(--pwb-accent,#b36b4e);font-size:11px;padding:1px}.pwb-annotation-editor{position:absolute;right:16px;top:54px;z-index:25;width:min(360px,calc(100% - 32px));max-height:calc(100% - 66px);overflow:auto;box-sizing:border-box;padding:16px;border:1px solid var(--pwb-line);border-radius:8px;background:var(--pwb-paper,#fdfcf9);box-shadow:0 8px 32px #0002;display:flex;flex-direction:column;gap:10px}.pwb-annotation-editor label{display:flex;flex-direction:column;gap:6px}.pwb-annotation-editor :is(textarea,select){padding:8px 10px;border:1px solid var(--pwb-line);border-radius:6px;background:var(--pwb-canvas);color:inherit;font:inherit}.pwb-annotation-editor>div{display:flex;gap:8px;flex-wrap:wrap}.pwb-annotation-editor small{font-size:12px;color:var(--pwb-muted)}.pwb-annotation-editor pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px}'
