import {AnnotationImage} from './annotation-image-view.tsx'
import {validateAnnotationImage} from './annotation-image.ts'
import {AnnotationHistory} from './annotation-history.tsx'
import {annotationRequest} from './annotation-records-api.ts'
import type {AnnotationRecord} from './annotation-records-api.ts'
import {revealAnnotationComposer} from './annotation-composer.ts'
import {useEffect,useLayoutEffect,useState,useRef} from 'react'
import type {RefObject} from 'react'
import type {Context} from '@deepseek-ai/cordis'
import type {AppRecipe} from './recipe-api.ts'
import {captureAnnotation,annotationText,annotationPositionMatches} from './annotation.ts'
import type {CanvasAnnotation} from './annotation.ts'
import type {} from './annotation-client.ts'
export function AnnotationLayer({canvas,recipe,pageId,instanceId,ctx,active,t,onRevealRole}:{onRevealRole?:()=>void;canvas:RefObject<HTMLDivElement>;recipe:AppRecipe;pageId:string;instanceId:string;ctx?:Context;active:boolean;t:(key:any)=>string}){
 const [aiming,setAiming]=useState(false),[selection,setSelection]=useState<CanvasAnnotation|null>(null),[requirement,setRequirement]=useState(''),[roleId,setRole]=useState(''),[records,setRecords]=useState<AnnotationRecord[]>([]),[history,setHistory]=useState(false),[storageError,setStorageError]=useState(''),[reload,setReload]=useState(0),[,setViewport]=useState(0),revision=useRef(0),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),start=useRef<{x:number;y:number}>(), pending=useRef<AbortController>(),[dragBox,setDragBox]=useState<CanvasAnnotation['box']|null>(null)
 const [screenshot,setScreenshot]=useState<File>()
 const toolbar=useRef<HTMLDivElement>(null),[annotationTop,setAnnotationTop]=useState(44)
 const selectImage=(file?:File)=>{try{if(file)validateAnnotationImage(file);setScreenshot(file);setError('')}catch(error){setError(error instanceof Error?error.message:String(error))}}
 useEffect(()=>setScreenshot(undefined),[selection?.id,recipe.appId,instanceId,pageId,recipe.version,active])
 const identity=JSON.stringify([recipe.appId,instanceId,pageId,recipe.version]),identityRef=useRef(identity);identityRef.current=identity
 useLayoutEffect(()=>{
  const view=canvas.current?.ownerDocument.defaultView
  const measure=()=>{if(canvas.current&&toolbar.current)setAnnotationTop(Math.max(44,toolbar.current.getBoundingClientRect().bottom-canvas.current.getBoundingClientRect().top))}
  measure();view?.addEventListener('resize',measure)
  const observer=typeof ResizeObserver==='undefined'?undefined:new ResizeObserver(measure)
  if(toolbar.current)observer?.observe(toolbar.current)
  if(canvas.current)observer?.observe(canvas.current)
  return()=>{view?.removeEventListener('resize',measure);observer?.disconnect()}
 },[canvas,identity,active,aiming,selection,history,notice,storageError])
 const editorStyle={top:annotationTop+10,maxHeight:'calc(100% - '+(annotationTop+22)+'px)'}
 useEffect(()=>{if(!active){pending.current?.abort();setBusy(false);setAiming(false);setSelection(null);setDragBox(null)}},[active])
 useEffect(()=>{if(!aiming&&!selection&&!history)return;const cancel=(event:KeyboardEvent)=>{if(event.key==='Escape'){pending.current?.abort();setBusy(false);setAiming(false);setSelection(null);setHistory(false);setDragBox(null)}};window.addEventListener('keydown',cancel);return()=>window.removeEventListener('keydown',cancel)},[aiming,selection,history])
 useEffect(()=>{
  const scroll=canvas.current?.querySelector('.pwb-recipe-page'),view=canvas.current?.ownerDocument.defaultView,changed=()=>setViewport(value=>value+1)
  scroll?.addEventListener('scroll',changed);view?.addEventListener('resize',changed)
  const observer=typeof ResizeObserver==='undefined'?undefined:new ResizeObserver(changed)
  if(canvas.current){observer?.observe(canvas.current);for(const module of canvas.current.querySelectorAll('[data-module-id]'))observer?.observe(module)}
  return()=>{scroll?.removeEventListener('scroll',changed);view?.removeEventListener('resize',changed);observer?.disconnect()}
 },[canvas,identity])
 useEffect(()=>{setBusy(false);setAiming(false);setSelection(null);setRecords([]);setHistory(false);setRequirement('');setError('');setNotice('');setDragBox(null);return()=>pending.current?.abort()},[identity])
 useEffect(()=>{
  if(!ctx||!active)return
  const controller=new AbortController(),current=++revision.current
  annotationRequest({action:'list',appId:recipe.appId,instanceId,pageId},controller.signal).then(result=>{if(!controller.signal.aborted&&revision.current===current){setRecords(result.records);setStorageError('')}}).catch(error=>{if(!controller.signal.aborted&&revision.current===current)setStorageError(error instanceof Error?error.message:String(error))})
  return()=>controller.abort()
 },[identity,reload,ctx,active])
 const archive=async(record:AnnotationRecord)=>{setBusy(true);setStorageError('');const current=++revision.current,captured=identity,controller=new AbortController();pending.current=controller;try{const result=await annotationRequest({action:'archive',appId:recipe.appId,instanceId,pageId,id:record.annotation.id,archived:!record.archived},controller.signal);if(!controller.signal.aborted&&identityRef.current===captured&&revision.current===current)setRecords(result.records)}catch(error){if(revision.current===current)setStorageError(error instanceof Error?error.message:String(error))}finally{if(revision.current===current)setBusy(false)}}
 const marks=records.filter(record=>!record.archived&&record.recipeVersion===recipe.version&&canvas.current&&annotationPositionMatches(canvas.current,record.annotation)).map(record=>record.annotation)
 const page=recipe.pages.find(page=>page.id===pageId);if(!page)return null
 const confirm=async()=>{if(!selection||!roleId)return;const captured=identity;const controller=new AbortController();pending.current=controller;setBusy(true);setError('');try{
  if(!recipe.roles.some(role=>role.id===roleId)||selection.moduleId&&!page.modules.some(module=>module.id===selection.moduleId))throw Error(t('annotationTargetChanged'))
  const bridge=ctx?.get('personalWorkbenchAnnotations');if(!bridge)throw Error(t('annotationUnavailable'))
  ++revision.current;const saved=await annotationRequest({action:'save',appId:recipe.appId,instanceId,pageId,recipeVersion:recipe.version,annotation:selection,requirement,roleId},controller.signal);controller.signal.throwIfAborted();if(identityRef.current!==captured)return;setRecords(saved.records);setStorageError('');setNotice(t('annotationSaved'))
  await bridge.append({appId:recipe.appId,instanceId,roleId},annotationText(recipe,instanceId,pageId,selection,requirement,screenshot),controller.signal,async()=>{onRevealRole?.();if(!canvas.current)throw Error(t('annotationTargetChanged'));await revealAnnotationComposer(canvas.current,{appId:recipe.appId,instanceId,roleId},controller.signal,t('annotationComposerMissing'))},screenshot)
  if(identityRef.current===captured){setSelection(null);setRequirement('');setNotice(t('annotationAdded'))}
 }catch(error){if(identityRef.current===captured)setError(error instanceof Error?error.message:String(error))}finally{if(identityRef.current===captured)setBusy(false)}}
 return <><style>{annotationStyles}</style><div ref={toolbar} className="pwb-annotation-toolbar" data-pwb-annotation-ui><button data-pwb-button type="button" aria-pressed={aiming} disabled={busy} onClick={()=>{setAiming(!aiming);setSelection(null);setHistory(false);setError('');setNotice('')}}>{t(aiming?'annotationCancel':'annotationStart')}</button><button data-pwb-button type="button" disabled={busy} aria-expanded={history} onClick={()=>{setHistory(!history);setSelection(null);setAiming(false)}}>{t('annotationHistory')} ({records.filter(record=>!record.archived).length})</button>{storageError&&<><span role="alert">{storageError}</span><button data-pwb-button type="button" disabled={busy} onClick={()=>setReload(value=>value+1)}>{t('retry')}</button></>}{aiming&&<small>{t('annotationHint')}</small>}{notice&&<span role="status">{notice}</span>}</div>
 {active&&history&&<AnnotationHistory style={editorStyle} records={records} busy={busy} onArchive={record=>{void archive(record)}} t={t}/>}
 {active&&marks.map((mark,index)=><span key={mark.id} className="pwb-annotation-mark" aria-label={t('annotationMark')+' '+(index+1)} style={{left:mark.box.x,top:mark.box.y,width:Math.max(mark.box.width,18),height:Math.max(mark.box.height,18)}}>{index+1}</span>)}
 {active&&aiming&&<div className="pwb-annotation-aim" style={{top:annotationTop}} role="region" aria-label={t('annotationArea')} onPointerDown={event=>{if(event.button!==0)return;start.current={x:event.clientX,y:event.clientY};event.currentTarget.setPointerCapture?.(event.pointerId)}} onPointerUp={event=>{if(!start.current||!canvas.current)return;const capture=captureAnnotation(canvas.current,start.current,{x:event.clientX,y:event.clientY},page);start.current=undefined;setDragBox(null);setSelection(capture);setRole(page.modules.find(module=>module.id===capture.moduleId)?.roleId??'');setAiming(false)}} onPointerMove={event=>{if(!start.current||!canvas.current)return;const r=canvas.current.getBoundingClientRect();setDragBox({x:Math.max(0,Math.min(start.current.x,event.clientX)-r.left),y:Math.max(annotationTop,Math.min(start.current.y,event.clientY)-r.top),width:Math.abs(event.clientX-start.current.x),height:Math.abs(event.clientY-start.current.y)})}} onPointerCancel={()=>{start.current=undefined;setDragBox(null);setAiming(false)}} onKeyDown={event=>{if(event.key==='Escape')setAiming(false)}} tabIndex={0}/>}
 {active&&(dragBox??selection?.box)&&<span className="pwb-annotation-mark" aria-hidden="true" style={{left:(dragBox??selection!.box).x,top:(dragBox??selection!.box).y,width:Math.max((dragBox??selection!.box).width,18),height:Math.max((dragBox??selection!.box).height,18)}}/>}
 {active&&selection&&<section className="pwb-annotation-editor" style={editorStyle} data-pwb-annotation-ui onPaste={event=>{if(busy)return;const file=[...event.clipboardData.files].find(file=>['image/png','image/jpeg','image/webp'].includes(file.type));if(file){event.preventDefault();selectImage(file)}}} aria-label={t('annotationEditor')}><strong>{selection.moduleTitle}</strong><small>{t('annotationPosition')}: {Math.round(selection.box.x)}, {Math.round(selection.box.y)} · {Math.round(selection.box.width)} × {Math.round(selection.box.height)}</small>{selection.limited&&<p role="status">{t(screenshot?'annotationLimitedImage':'annotationLimited')}</p>}<AnnotationImage file={screenshot} busy={busy} t={t} onChange={selectImage}/>{selection.text&&<details><summary>{t('annotationContext')}</summary><pre>{selection.text}</pre></details>}<label>{t('annotationRequirement')}<textarea aria-label={t('annotationRequirement')} rows={3} maxLength={2000} value={requirement} disabled={busy} onChange={event=>setRequirement(event.target.value)}/></label><label>{t('annotationRole')}<select aria-label={t('annotationRole')} value={roleId} disabled={busy} onChange={event=>setRole(event.target.value)}><option value="">{t('annotationChooseRole')}</option>{recipe.roles.map(role=><option key={role.id} value={role.id}>{role.name}</option>)}</select></label><div><button data-pwb-button data-variant="primary" type="button" disabled={busy||!roleId||!requirement.trim()} onClick={()=>{void confirm()}}>{t('annotationAppend')}</button><button data-pwb-button type="button" disabled={busy} onClick={()=>{setSelection(null);setError('')}}>{t('annotationCancel')}</button></div><small>{t('annotationNoSend')}</small>{error&&<p role="alert">{error}</p>}</section>}
 </>
}
const annotationStyles=' .pwb-annotation-toolbar{position:relative;z-index:10;min-height:44px;flex-wrap:wrap;flex-shrink:0;display:flex;align-items:center;gap:10px;padding:4px 16px;box-sizing:border-box}.pwb-annotation-toolbar small,.pwb-annotation-toolbar span{font-size:12px;color:var(--pwb-muted)}.pwb-annotation-aim{position:absolute;inset:44px 0 0;z-index:20;cursor:crosshair;background:#7096b60b;touch-action:none}.pwb-annotation-mark{position:absolute;z-index:15;pointer-events:none;box-sizing:border-box;border:2px solid var(--pwb-accent,#b36b4e);border-radius:4px;color:var(--pwb-accent,#b36b4e);font-size:11px;padding:1px}.pwb-annotation-editor{position:absolute;right:16px;top:54px;z-index:25;width:min(360px,calc(100% - 32px));max-height:calc(100% - 66px);overflow:auto;box-sizing:border-box;padding:16px;border:1px solid var(--pwb-line);border-radius:8px;background:var(--pwb-paper,#fdfcf9);box-shadow:0 8px 32px #0002;display:flex;flex-direction:column;gap:10px}.pwb-annotation-editor label{display:flex;flex-direction:column;gap:6px}.pwb-annotation-editor :is(textarea,select){padding:8px 10px;border:1px solid var(--pwb-line);border-radius:6px;background:var(--pwb-canvas);color:inherit;font:inherit}.pwb-annotation-editor select{min-height:38px}.pwb-annotation-editor article{padding:10px 0;border-bottom:1px solid var(--pwb-line)}.pwb-annotation-editor article>button{margin-top:8px}.pwb-annotation-editor>div{display:flex;gap:8px;flex-wrap:wrap}.pwb-annotation-editor small{font-size:12px;color:var(--pwb-muted)}.pwb-annotation-editor pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px}'
