import {useEffect,useState,useSyncExternalStore} from 'react'
import { RecipeConnections } from './recipe-connections.tsx'
import { displayCatalog, listRecipeTemplates } from './display-api.ts'
import {isRecipeForm} from './recipe-form.ts'
import {RecipeRolesEditor} from './recipe-role-editor.tsx'
import type {AppRecipe,RecipeRecord,RecipeRequest} from './recipe-api.ts'
import {RecipePage} from './recipe-view.tsx'
import {GenerationEditor} from './generation-editor.tsx'
import {recipeEditorStyles} from './recipe-editor-styles.ts'
export async function recipeRequest(request:RecipeRequest){const response=await fetch('/api/personal-workbench/recipes',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify(request)});const value=await response.json();if(!response.ok)throw new Error(value.error??'Recipe request failed');return value as {recipes?:RecipeRecord[];record?:RecipeRecord;recipe?:AppRecipe}}
export function RecipeEditor({t,refresh}:{t:(key:any)=>string;refresh:()=>Promise<void>}){
 useSyncExternalStore(displayCatalog.subscribe,displayCatalog.getSnapshot,displayCatalog.getSnapshot)
 const [records,setRecords]=useState<RecipeRecord[]>([]),[selected,setSelected]=useState(''),[text,setText]=useState(''),[preview,setPreview]=useState<AppRecipe|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[previewPage,setPreviewPage]=useState(''),[generating,setGenerating]=useState(false),[step,setStep]=useState(0)
 const locked=busy||generating
 const load=async()=>{const data=await recipeRequest({action:'catalog'});setRecords(data.recipes??[])}
 useEffect(()=>{void load().catch(e=>setError(String(e.message)))},[])
 let edited:AppRecipe|undefined;try{const parsed:unknown=JSON.parse(text);if(isRecipeForm(parsed))edited=parsed}catch{}
 const change=(update:(recipe:AppRecipe)=>void)=>{if(!edited)return;const copy=structuredClone(edited);update(copy);setText(JSON.stringify(copy,null,2));setPreview(null)}
 const row=records.find(r=>r.appId===selected)
 const run=async(action:()=>Promise<void>)=>{setBusy(true);setError('');try{await action()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 return <><style>{recipeEditorStyles}</style><details className="pwb-recipe-editor"><summary>{t('recipeEditor')}</summary><p className="pwb-recipe-help">{t('recipeDraftHelp')}</p><div className="pwb-recipe-toolbar"><button data-pwb-button type="button" disabled={locked} onClick={()=>{const appId='app.'+crypto.randomUUID();const recipe:AppRecipe={schemaVersion:1,appId,version:1,name:t('recipeNewName'),description:'',pages:[{id:'home',label:t('recipeHome'),layout:'grid',modules:[{id:'summary',type:'stats',title:t('recipeSummary'),config:{}},{id:'items',type:'list',title:t('recipeItems'),config:{}}]}],connections:[],roles:[]};setStep(0);setSelected(appId);setText(JSON.stringify(recipe,null,2));setPreview(null)}}>{t('recipeCreate')}</button>{listRecipeTemplates().map(template=><button data-pwb-button key={template.id} disabled={locked} onClick={()=>{void run(async()=>{const recipe=await template.create();const existing=records.find(record=>record.appId===recipe.appId);recipe.version=Math.max(recipe.version,(existing?.running?.version??0)+1);setStep(0);setSelected(recipe.appId);setText(JSON.stringify(recipe,null,2));setPreview(null)})}}>{template.label}</button>)}<select aria-label={t('recipeSelect')} value={selected} disabled={locked} onChange={e=>{setStep(0);setSelected(e.target.value);const record=records.find(r=>r.appId===e.target.value);setText(record?JSON.stringify(record.draft,null,2):'');setPreview(null)}}><option value="">{t('recipeSelect')}</option>{records.map(r=><option key={r.appId} value={r.appId}>{r.draft.name} · {r.revision}</option>)}</select></div>
 {text&&<nav className="pwb-recipe-steps" aria-label={t('recipeSteps')}>{['recipeBasics','recipeConnections','recipeRolesStep','recipePreviewStep'].map((label,index)=><button data-pwb-button key={label} type="button" disabled={locked} aria-current={step===index?'step':undefined} onClick={()=>setStep(index)}>{t(label)}</button>)}</nav>}
 <div hidden={step!==0}><GenerationEditor t={t} target={{appId:selected||'app.'+crypto.randomUUID(),version:Math.max(edited?.version??1,(row?.running?.version??0)+1),expectedRevision:row?.revision??0}} onBusy={setGenerating} onDraft={async record=>{setStep(0);setSelected(record.appId);setText(JSON.stringify(record.draft,null,2));setPreview(null);await load()}}/></div>
 {edited&&step===1&&<fieldset disabled={locked}><RecipeConnections recipe={edited} change={change} t={t}/></fieldset>}
 {edited&&step===0&&<fieldset disabled={locked}><legend>{t('recipeBasics')}</legend><label>{t('recipeName')}<input aria-label={t('recipeName')} value={edited.name} onChange={e=>change(r=>{r.name=e.target.value})}/></label><label>{t('recipeDescription')}<input aria-label={t('recipeDescription')} value={edited.description} onChange={e=>change(r=>{r.description=e.target.value})}/></label><label>{t('recipeVersion')}<input type="number" min="1" aria-label={t('recipeVersion')} value={edited.version} onChange={e=>change(r=>{r.version=Number(e.target.value)})}/></label>{edited.pages.map((page,index)=><fieldset key={page.id}><legend>{t('recipePage')}: {page.id}</legend><label>{t('recipePageLabel')}<input value={page.label} onChange={e=>change(r=>{r.pages[index].label=e.target.value})}/></label><label>{t('recipeLayout')}<select aria-label={t('recipeLayout')+': '+page.id} value={page.layout} onChange={e=>change(r=>{r.pages[index].layout=e.target.value as 'stack'|'grid'|'split'})}>{(['stack','grid','split'] as const).map(layout=><option key={layout} value={layout}>{t('recipeLayout'+layout)}</option>)}</select></label>{(['stats','list','detail','filter'] as const).map(type=><label key={type}><input type="checkbox" aria-label={t('recipeModule'+type)+': '+page.id} checked={page.modules.some(m=>m.type===type)} onChange={e=>change(r=>{r.pages[index].modules=e.target.checked?[...r.pages[index].modules,{id:page.id+'.'+type,type,title:t('recipeModule'+type),config:{}}]:r.pages[index].modules.filter(m=>m.type!==type)})}/>{t('recipeModule'+type)}</label>)}</fieldset>)}<button data-pwb-button onClick={()=>change(r=>{const id='page.'+crypto.randomUUID();r.pages.push({id,label:t('recipeHome'),layout:'stack',modules:[]})})}>{t('recipeAddPage')}</button></fieldset>}
 {edited&&step===2&&<fieldset disabled={locked}><legend>{t('recipeRolesStep')}</legend><RecipeRolesEditor recipe={edited} change={change} t={t}/></fieldset>}
 {text&&<><details className="pwb-recipe-advanced"><summary>{t('recipeAdvanced')}</summary><label>{t('recipeConfiguration')}<textarea aria-label={t('recipeConfiguration')} style={{display:'block',width:'100%',minHeight:280}} value={text} disabled={locked} onChange={e=>{setText(e.target.value);setPreview(null)}}/></label></details><button data-pwb-button data-variant="primary" disabled={locked} onClick={()=>{void run(async()=>{const recipe:unknown=JSON.parse(text);if(!isRecipeForm(recipe))throw new Error(t('recipeInvalidConfiguration'));if(recipe.appId!==selected)throw new Error(t('recipeIdentityFixed'));const saved=await recipeRequest({action:'save',expectedRevision:row?.revision??0,recipe});setText(JSON.stringify(saved.record!.draft,null,2));await load();setPreview(null)})}}>{t('recipeSave')}</button>{step===3&&<><p>{t('recipePreviewStepHelp')}</p><button data-pwb-button disabled={locked||!row||JSON.stringify(row.draft,null,2)!==text} onClick={()=>{void run(async()=>{const data=await recipeRequest({action:'preview',appId:selected,expectedRevision:row!.revision});setPreview(data.recipe!);setPreviewPage(data.recipe!.pages[0].id);})}}>{t('recipePreview')}</button><button data-pwb-button data-variant="primary" disabled={locked||!row||!preview} onClick={()=>{void run(async()=>{await recipeRequest({action:'activate',appId:selected,expectedRevision:row!.revision});await load();await refresh();setPreview(null)})}}>{t('recipeActivate')}</button></>}</>}
 {text&&<nav className="pwb-recipe-navigation" aria-label={t('recipeStepNavigation')}><button data-pwb-button type="button" disabled={locked||step===0} onClick={()=>setStep(step-1)}>{t('recipeBack')}</button><span role="status">{step+1} / 4 · {t(['recipeBasics','recipeConnections','recipeRolesStep','recipePreviewStep'][step])}</span><button data-pwb-button type="button" disabled={locked||step===3||!edited} onClick={()=>setStep(step+1)}>{t('recipeNext')}</button></nav>}
 {text&&!edited&&<p role="alert">{t('recipeInvalidConfiguration')}</p>}
 {error&&<p role="alert">{t('recipeError')}: {error}</p>}{preview&&step===3&&<section aria-label={t('recipePreview')}><p>{t('recipePreviewHelp')}</p><nav>{preview.pages.map(page=><button data-pwb-button key={page.id} aria-pressed={previewPage===page.id} onClick={()=>setPreviewPage(page.id)}>{page.label}</button>)}</nav><RecipePage recipe={preview} appId={preview.appId} instanceId={'preview.'+selected} pageId={previewPage} preview t={t}/></section>}</details></>
}
