import {capabilityDomain} from './capability-domain.ts'
import type { Context } from '@deepseek-ai/cordis'
import type { IncomingMessage,ServerResponse } from 'node:http'
import { defineDomain,domainTable } from '@deepseek-ai/dsh-storage-domain'
import type { AppRecipe,RecipeRecord,PersonalWorkbenchRecipes,RecipeModuleDefinition } from './recipe-api.ts'
import {recipeSchema,recipeRecordSchema,recipeRequestSchema,structuralErrors} from './recipe-schema.ts'
export const recipeDomain=defineDomain({name:'personal_workbench_recipes',version:1,tables:{recipes:domainTable<string,RecipeRecord>(recipeRecordSchema)}})
export async function installRecipes(ctx:Context){
 const domain=await ctx.storageDomain.open(recipeDomain),table=domain.table('recipes'),modules=new Map<string,RecipeModuleDefinition>();let closing=false,tail=Promise.resolve();const requests=new Set<Promise<void>>(), reserved=new Set<string>()
 for(const id of ['stats','list','detail','filter','role-chat'])modules.set(id,{id})
 const serial=<T>(run:()=>Promise<T>)=>{const task=tail.catch(()=>{}).then(()=>{if(closing)throw new Error('Recipes unavailable');return run()});tail=task.then(()=>{},()=>{});return task}
 const read=(appId:string,expectedRevision:number)=>{const row=table.get(appId);if(!row)throw new Error('Recipe not found');if(row.appId!==appId)throw new Error('Recipe identity mismatch');if(row.revision!==expectedRevision)throw new Error('Recipe changed; refresh and retry');return row}
 const validate=async(recipe:AppRecipe)=>{
  recipeSchema.parse(recipe);if(reserved.has(recipe.appId))throw new Error('Application identity belongs to an installed application');const errors=structuralErrors(recipe)
  for(const page of recipe.pages)for(const module of page.modules){const definition=modules.get(module.type);if(!definition)errors.push(`Unavailable module: ${module.type}`);else errors.push(...(definition.validate?.(module,recipe)??[]))}
  // The initial release supports owned data only; cross-app access needs an explicit registered adapter in a later slice.
  for(const connection of recipe.connections)if(connection.sourceAppId!==recipe.appId)errors.push(`Unavailable data connection: ${connection.id}`)
  if(recipe.roles.length){const capabilities=await ctx.storageDomain.open(capabilityDomain);try{const managed=[...capabilities.table('agents').entries()].map(([,row])=>row);const presets=await ctx.get('agentPresets')?.list();for(const role of recipe.roles){const preset=presets?.find(p=>p.id===role.presetId);const capability=managed.find(a=>'my-dsh.'+a.id===role.presetId);if(!preset||preset.broken||(role.presetId.startsWith('my-dsh.')&&(!capability||!capability.userInvocable)))errors.push(`Unavailable Agent: ${role.presetId}`);if(role.skillNames.length){const snapshot=await ctx.get('skills')?.snapshot({scope:ctx});for(const name of role.skillNames)if(!snapshot?.complete||!snapshot.skills.some(s=>s.name===name&&s.invocation.userInvocable))errors.push(`Unavailable Skill: ${name}`)}}}finally{await capabilities.close()}}
  if(errors.length)throw new Error(errors.join('; '))
 }
 const service:PersonalWorkbenchRecipes={reserveAppId:appId=>{if(reserved.has(appId))throw new Error('Application identity already reserved');if(table.get(appId)?.running)throw new Error('Application identity belongs to a running recipe');reserved.add(appId);return()=>{reserved.delete(appId)}},list:()=>[...table.entries()].map(([key,row])=>{if(key!==row.appId)throw new Error('Recipe identity mismatch');return structuredClone(row)}),registerModule:definition=>{if(modules.has(definition.id))throw new Error('Duplicate module');modules.set(definition.id,definition);return()=>{if(modules.get(definition.id)===definition)modules.delete(definition.id)}},save:(recipe,expectedRevision)=>serial(async()=>{const parsed=recipeSchema.parse(recipe);if(reserved.has(parsed.appId))throw new Error('Application identity belongs to an installed application');const current=table.get(parsed.appId);if((current?.revision??0)!==expectedRevision)throw new Error('Recipe changed; refresh and retry');if(current?.running&&parsed.version<=current.running.version)throw new Error('Draft version must exceed running version');const row:RecipeRecord={appId:parsed.appId,revision:expectedRevision+1,draft:parsed,...(current?.running?{running:current.running}:{})};await table.put(row.appId,row);return structuredClone(row)}),preview:(appId,expectedRevision)=>serial(async()=>{const row=read(appId,expectedRevision);await validate(row.draft);return structuredClone(row.draft)}),activate:(appId,expectedRevision)=>serial(async()=>{const current=read(appId,expectedRevision);await validate(current.draft);if(reserved.has(appId))throw new Error('Application identity belongs to an installed application');const row={...current,revision:current.revision+1,running:structuredClone(current.draft)};await table.put(appId,row);return structuredClone(row)})}
 const remove=ctx.reflect.provide('personalWorkbenchRecipes',service)
 const dispatch=async(req:IncomingMessage,res:ServerResponse)=>{const respond=(status:number,value:unknown)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(value))};try{const rejection=ctx.connection.requestRejection(req);if(rejection!==undefined){respond(rejection,{error:'Authenticated same-origin request required'});return}if(req.method!=='POST'){res.setHeader('allow','POST');respond(405,{error:'POST required'});return}if(!req.headers['content-type']?.startsWith('application/json')){respond(415,{error:'JSON required'});return}let size=0;const chunks:Buffer[]=[];for await(const chunk of req){const bytes=Buffer.from(chunk);size+=bytes.length;if(size>262144){respond(413,{error:'Request too large'});return}chunks.push(bytes)}let input;try{input=JSON.parse(Buffer.concat(chunks).toString('utf8'))}catch{respond(400,{error:'Invalid JSON'});return}const parsed=recipeRequestSchema.safeParse(input);if(!parsed.success){respond(400,{error:parsed.error.issues.map(i=>i.path.join('.')+': '+i.message).join('; ')});return}const data=parsed.data;if(data.action==='catalog')respond(200,{version:1,recipes:service.list()});else if(data.action==='save')respond(200,{record:await service.save(data.recipe,data.expectedRevision)});else if(data.action==='preview')respond(200,{recipe:await service.preview(data.appId,data.expectedRevision)});else respond(200,{record:await service.activate(data.appId,data.expectedRevision)})}catch(error){respond(409,{error:error instanceof Error?error.message:'Recipe request failed'})}}
 return {service,handle:(req:IncomingMessage,res:ServerResponse)=>{if(closing){res.writeHead(503);res.end();return Promise.resolve()}const task=dispatch(req,res);requests.add(task);void task.finally(()=>requests.delete(task)).catch(()=>{});return task},dispose:async()=>{closing=true;remove();await Promise.allSettled([...requests,tail]);await domain.close()}}
}
