import { PreparedTaskEditor } from './task-view.tsx'
import type { Context } from '@deepseek-ai/cordis'
import type { PropsRenderFactories } from '@deepseek-ai/dsh-client-ui-slots'
import type { ComponentType } from 'react'
import type { AppRecipe,RecipeModule } from './recipe-api.ts'
export interface RecipeModuleProps { recipe:AppRecipe; module:RecipeModule; appId:string; instanceId:string; preview:boolean; ctx?:Context; pageId:string; t:(key:any)=>string; renderFactorySlot?:PropsRenderFactories['renderFactorySlot'] }
const renderers=new Map<string,ComponentType<RecipeModuleProps>>()
/** Renderers are installed code owned by plugins; recipes contain no executable source. */
export function registerRecipeModuleRenderer(id:string,view:ComponentType<RecipeModuleProps>):()=>void{if(renderers.has(id))throw new Error('Duplicate module renderer');renderers.set(id,view);return()=>{if(renderers.get(id)===view)renderers.delete(id)}}
export function RecipePage({recipe,pageId,appId,instanceId,preview=false,t,ctx,renderFactorySlot}:{recipe:AppRecipe;pageId:string;appId:string;instanceId:string;preview?:boolean;t:(key:any)=>string;ctx?:Context;renderFactorySlot?:PropsRenderFactories['renderFactorySlot']}){
 const page=recipe.pages.find(p=>p.id===pageId);if(!page)return <p role="alert">{t('recipeMissingPage')}</p>
 return <div data-recipe-version={recipe.version} data-preview={preview} style={{display:'grid',gap:16,gridTemplateColumns:page.layout==='stack'?'1fr':'repeat(2,minmax(0,1fr))'}}>{page.modules.map(module=>{const View=renderers.get(module.type);return <section key={module.id}><h3>{module.title}</h3>{View?<View recipe={recipe} module={module} appId={appId} instanceId={instanceId} preview={preview} ctx={ctx} pageId={pageId} t={t} renderFactorySlot={renderFactorySlot}/>:['stats','list','detail','filter'].includes(module.type)?<p role="status">{t('recipeEmptyModule')}</p>:<p role="alert">{t('recipeMissingModule')}: {module.type}</p>}{!preview&&ctx&&module.roleId&&typeof module.config.taskPrompt==='string'&&module.config.taskPrompt.trim()&&<><button disabled={!ctx.get('personalWorkbenchTasks')} onClick={()=>ctx.get('personalWorkbenchTasks')?.prepare({key:{appId,instanceId,roleId:module.roleId!},task:String(module.config.taskPrompt),source:{pageId,moduleId:module.id,label:module.title},context:typeof module.config.taskContext==='string'?[{id:module.id,label:module.title,source:pageId+'/'+module.id,text:module.config.taskContext}]:[]})}>{t('taskPrepared')}</button><PreparedTaskEditor ctx={ctx} bindingKey={{appId,instanceId,roleId:module.roleId}} t={t}/></>}</section>})}</div>
}
