import type {AppRecipe,RecipeModule} from './recipe-api.ts'
import {contentTypes} from './content-catalog.ts'
import {listDisplaySources} from './display-api.ts'
import {RecipeRoleSettings} from './recipe-role-settings.tsx'
export function RecipeModuleEditor({pageIndex,recipe,change,t,moduleId}:{pageIndex:number;recipe:AppRecipe;change:(update:(r:AppRecipe)=>void)=>void;t:(key:any)=>string;moduleId?:string}){
 const page=recipe.pages[pageIndex],sources=listDisplaySources(recipe.appId)
 const update=(index:number,fn:(m:RecipeModule)=>void)=>change(r=>fn(r.pages[pageIndex].modules[index]))
 return <section className="pwb-module-editor">{!moduleId&&<><h4>{t('moduleContents')}</h4><p>{t('moduleContentsHelp')}</p></>}{page.modules.map((m,index)=>(!moduleId||m.id===moduleId)&&<fieldset className="pwb-module-card" key={m.id}><legend>{t('modulePane')} {index+1}</legend>
 <label>{t('moduleTitle')}<input aria-label={t('moduleTitle')+': '+m.id} value={m.title} onChange={e=>update(index,m=>{m.title=e.target.value})}/></label>
 <label>{t('moduleType')}<select aria-label={t('moduleType')+': '+m.id} value={m.type} onChange={e=>update(index,m=>{m.type=e.target.value;m.config=m.type==='custom'?{mode:'generate'}:{};delete m.connectionId;delete m.roleId})}>{!contentTypes.includes(m.type as any)&&<option value={m.type}>{m.type}</option>}{contentTypes.map(type=><option key={type} value={type}>{t('recipeModule'+type)}</option>)}</select></label>
 {m.type==='custom'&&<label>{t('moduleSource')}<select aria-label={t('moduleSource')+': '+m.id} value={String(m.config.mode??'generate')} onChange={e=>update(index,m=>{m.config={mode:e.target.value}})}>{['generate','url','file'].map(mode=><option key={mode} value={mode}>{t('moduleSource'+mode)}</option>)}</select></label>}
 {(['website','animation'].includes(m.type)||(m.type==='custom'&&m.config.mode==='url'))&&<label>{t('moduleUrl')}<input aria-label={t('moduleUrl')+': '+m.id} type="url" placeholder="https://" value={String(m.config.url??'')} onChange={e=>update(index,m=>{m.config.url=e.target.value})}/></label>}
 {m.type==='resources'&&<label>{t('moduleDirectory')}<input aria-label={t('moduleDirectory')+': '+m.id} placeholder={t('moduleRoot')} value={String(m.config.basePath??'')} onChange={e=>update(index,m=>{m.config.basePath=e.target.value})}/></label>}
 {m.type==='custom'&&m.config.mode==='file'&&<label>{t('moduleFile')}<input aria-label={t('moduleFile')+': '+m.id} placeholder="pages/example.html" value={String(m.config.path??'')} onChange={e=>update(index,m=>{m.config.path=e.target.value})}/></label>}
 {m.type==='custom'&&m.config.mode==='generate'&&<label>{t('moduleRequirement')}<textarea aria-label={t('moduleRequirement')+': '+m.id} value={String(m.config.requirement??'')} maxLength={2000} onChange={e=>update(index,m=>{m.config.requirement=e.target.value})}/></label>}
 {['stats','list','filter','detail','chart','map'].includes(m.type)&&<><label>{t('recipeModuleConnection')}<select aria-label={t('recipeModuleConnection')+': '+m.id} value={m.connectionId??''} onChange={e=>update(index,m=>{if(e.target.value)m.connectionId=e.target.value;else delete m.connectionId})}><option value="">{t('recipeEmptyModule')}</option>{recipe.connections.map(c=><option key={c.id} value={c.id}>{c.sourceAppId} / {c.resource}</option>)}</select></label><label>{t('recipeSource')}<select aria-label={t('recipeSource')+': '+m.id} value="" onChange={e=>{const source=sources.find(s=>s.resource===e.target.value);if(source)change(copy=>{let connection=copy.connections.find(c=>c.resource===source.resource&&c.sourceAppId===source.appId);if(!connection){connection={id:'data.'+crypto.randomUUID(),sourceAppId:source.appId,resource:source.resource};copy.connections.push(connection)}copy.pages[pageIndex].modules[index].connectionId=connection.id})}}><option value="">{t('recipeAddConnection')}</option>{sources.map(source=><option key={source.resource} value={source.resource}>{source.label}</option>)}</select></label>{!sources.length&&!recipe.connections.length&&<small>{t('displayUnavailable')}</small>}</>}
 {(['chart','map'].includes(m.type))&&<details open><summary>{t('displayFieldMapping')}</summary>{(m.type==='chart'?['valueField']:['latitudeField','longitudeField']).map(field=><label key={field}>{t('display'+field)}<input aria-label={t('display'+field)+': '+m.id} value={String(m.config[field]??'')} onChange={event=>update(index,m=>{m.config[field]=event.target.value})}/></label>)}</details>}
 <label>{t('recipeTaskRole')}<select aria-label={t('recipeTaskRole')+': '+m.id} value={m.roleId??''} onChange={e=>update(index,m=>{if(e.target.value)m.roleId=e.target.value;else delete m.roleId})}><option value="">{t('recipeChooseRole')}</option>{recipe.roles.map(role=><option key={role.id} value={role.id}>{role.name}</option>)}</select></label>
 <RecipeRoleSettings recipe={recipe} pageIndex={pageIndex} moduleIndex={index} change={change} t={t}/>
 {['stats','list','filter','detail','chart','map'].includes(m.type)&&m.roleId&&<label>{t('displayTaskMode')}<select aria-label={t('displayTaskMode')+': '+m.id} value={String(m.config.taskSkill??'')} onChange={event=>update(index,m=>{if(event.target.value)m.config.taskSkill=event.target.value;else delete m.config.taskSkill})}><option value="">{t('displayTaskAnalyze')}</option><option value="workbench-data-display">{t('displayTaskBuild')}</option></select></label>}
 {!['role-chat','custom','empty'].includes(m.type)&&m.roleId&&<label>{t('recipeTaskPrompt')}<textarea aria-label={t('recipeTaskPrompt')+': '+m.id} value={String(m.config.taskPrompt??'')} onChange={e=>update(index,m=>{m.config.taskPrompt=e.target.value})}/></label>}
 {!moduleId&&<button data-pwb-button type="button" onClick={()=>change(r=>{r.pages[pageIndex].modules.splice(index,1)})}>{t('moduleRemove')}</button>}</fieldset>)}
 {!moduleId&&<button data-pwb-button type="button" onClick={()=>change(r=>{r.pages[pageIndex].modules.push({id:'module.'+crypto.randomUUID(),type:'empty',title:'',config:{}})})}>{t('moduleAdd')}</button>}</section>
}
