/** Scoped workspace material; never targets DSH or Better Sidebar selectors. */
export const workspaceStyles = `
.pwb-workspace{--pwb-canvas:#faf9f6;--pwb-paper:#fff;--pwb-ink:#292724;--pwb-muted:#68655f;--pwb-line:#dedbd5;--pwb-accent:#bd553e;position:fixed;inset:12px;display:flex;flex-direction:column;min-width:0;min-height:0;pointer-events:auto;z-index:2;background:var(--pwb-canvas);color:var(--pwb-ink);font:14px/1.5 system-ui,-apple-system,"Segoe UI","Microsoft YaHei",sans-serif;letter-spacing:0;box-shadow:0 2px 16px #0002;border-radius:6px;overflow:hidden}
.pwb-workspace[hidden]{display:none}.pwb-workspace *{box-sizing:border-box;letter-spacing:0}
.pwb-workspace button{font:inherit;color:inherit;border:0;border-radius:4px;background:transparent;cursor:pointer;display:inline-flex;align-items:center;justify-content:center;gap:6px;min-width:30px;min-height:30px;padding:4px;flex-shrink:0}
.pwb-workspace button:hover{background:#edeae5}.pwb-workspace button:disabled{cursor:default;opacity:.65}.pwb-workspace button[aria-pressed=true],.pwb-workspace button[aria-selected=true]{color:var(--pwb-accent);background:#f5e5df}
.pwb-workspace :focus-visible{outline:2px solid #237b78;outline-offset:-2px}.pwb-workspace svg{flex-shrink:0}
.pwb-top{display:flex;align-items:center;gap:8px;padding:8px 12px;border-bottom:1px solid var(--pwb-line)}.pwb-top strong{font-size:14px;font-weight:600;flex:1;min-width:0;overflow-wrap:anywhere}
.pwb-body{display:flex;flex:1;min-height:0;min-width:0}.pwb-catalog{width:230px;flex-shrink:0;display:flex;flex-direction:column;border-right:1px solid var(--pwb-line);min-height:0}
.pwb-search{display:flex;align-items:center;gap:6px;margin:12px 10px 6px;padding:5px 8px;background:var(--pwb-paper);border:1px solid var(--pwb-line);border-radius:4px}.pwb-search input{min-width:0;width:100%;border:0;background:transparent;font:inherit;color:inherit}
.pwb-hidden{font-size:12px;display:flex;align-items:center;gap:4px;padding:0 10px 8px}.pwb-list{overflow:auto;min-height:0;flex:1}.pwb-app{padding:8px 10px;border-bottom:1px solid var(--pwb-line)}.pwb-open{width:100%;justify-content:flex-start!important;text-align:left}.pwb-open span{overflow-wrap:anywhere;min-width:0}.pwb-meta{font-size:12px;color:var(--pwb-muted);overflow-wrap:anywhere;padding-left:4px}.pwb-app-tools{display:flex;gap:3px;margin-top:4px}.pwb-dependencies{font-size:12px;color:#966a18;overflow-wrap:anywhere;margin:4px 0}.pwb-empty{padding:12px;color:var(--pwb-muted)}
.pwb-workarea{flex:1;display:flex;flex-direction:column;min-width:0;min-height:0}.pwb-taskbar{display:flex;gap:4px;flex:none;min-height:39px;padding:4px 8px;border-bottom:1px solid var(--pwb-line);overflow-x:auto}.pwb-taskbar button{max-width:220px;font-size:13px}.pwb-taskbar span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.pwb-stage{position:relative;flex:1;min-width:0;min-height:0;overflow:hidden}
.pwb-window{position:absolute;display:flex;flex-direction:column;min-width:0;min-height:0;background:var(--pwb-paper);border:1px solid var(--pwb-line);border-radius:6px;overflow:hidden}.pwb-window[hidden]{display:none}.pwb-window-header{display:flex;align-items:center;padding:4px;gap:2px;border-bottom:1px solid var(--pwb-line);flex:none}.pwb-move{flex:1;min-width:0!important;justify-content:flex-start!important;touch-action:none}.pwb-move span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.pwb-pages{display:flex;gap:4px;padding:4px 8px;border-bottom:1px solid var(--pwb-line);overflow:auto;flex:none}.pwb-pages button{font-size:13px;white-space:nowrap}.pwb-content{flex:1;min-height:0;min-width:0;overflow:auto}.pwb-content img{max-width:100%;height:auto}.pwb-content table{max-width:100%}.pwb-resize{display:flex;gap:6px;align-items:center;font-size:12px;padding:4px 8px;border-top:1px solid var(--pwb-line);flex:none}.pwb-resize input{min-width:0;width:80px;flex:1;accent-color:var(--pwb-accent)}.pwb-notice{margin:0;padding:6px 12px;font-size:12px;color:#966a18;background:#fff5d8}
@media(max-width:700px){.pwb-workspace{inset:0;border-radius:0}.pwb-body{flex-direction:column}.pwb-catalog{width:100%;max-height:180px;border-right:0;border-bottom:1px solid var(--pwb-line)}.pwb-search{margin:6px 8px}.pwb-hidden{padding-bottom:4px}.pwb-list{display:flex;gap:0}.pwb-app{min-width:180px;max-width:230px;border-right:1px solid var(--pwb-line);border-bottom:0}.pwb-top{padding:4px 8px}.pwb-window{border-radius:0}.pwb-pages{padding:2px 4px}}
`
