import { optionalWorkbenchClient } from './optional-workbench-client.ts'
const controlStyles = optionalWorkbenchClient?.controlStyles ?? `
.kg-study-shell{--pwb-canvas:#f7f5f0;--pwb-paper:#fdfcf9;--pwb-ink:#2e2b26;--pwb-muted:#736c62;--pwb-line:#d7d0c5;--pwb-accent:#a44c32}
.kg-study-shell [data-pwb-button]{min-height:36px;padding:7px 12px;border:1px solid var(--pwb-line);border-radius:7px;background:var(--pwb-paper);color:var(--pwb-ink);font:inherit;cursor:pointer}
.kg-study-shell [data-pwb-button]:focus-visible{outline:2px solid var(--pwb-accent);outline-offset:3px}
.kg-study-shell [data-pwb-button]:disabled{opacity:.48;cursor:not-allowed}
.kg-study-shell [data-pwb-button][data-variant=primary]{background:var(--pwb-accent);color:#fffaf6}
`
/** Scoped styles: native DSH navigation and conversation controls keep their own theme. */
export const learningStyles = `
.kg-study-shell{display:flex;flex-direction:column;flex:1;min-width:0;min-height:0;height:100%;background:var(--pwb-canvas, #f7f5f0);outline:none}.kg-study-shell[hidden]{display:none}
.pwb-project:has(.kg-study-shell[data-study=true]:not([hidden]))>.pwb-pages,.pwb-project-shell:has(.kg-study-shell[data-study=true]:not([hidden]))>.pwb-top{visibility:hidden}
.kg-study-shell[data-study=true]{position:absolute;inset:12px;height:auto;z-index:5;border:1px solid #d7d0c5;border-radius:12px;box-shadow:0 12px 36px #3e302218;overflow:hidden}
.kg-study-toolbar{display:flex;align-items:center;justify-content:space-between;gap:12px;flex:none;padding:12px 18px;background:var(--pwb-paper, #fdfcf9);border-bottom:1px solid #d7d0c5}.kg-study-toolbar>div{display:flex;flex-direction:column;gap:2px}.kg-study-toolbar strong{font-size:15px}.kg-study-toolbar span{font-size:12px;color:#736c62}.kg-study-toolbar button{display:inline-flex;align-items:center;gap:7px;padding:8px 12px!important;border:1px solid #d7d0c5!important;border-radius:8px!important;font-size:13px!important;white-space:nowrap}.kg-study-toolbar .kg-study-launch{background:#a44c32!important;color:white!important;border-color:#a44c32!important}
.kg-study-pages{display:flex;gap:6px;padding:8px 18px;background:var(--pwb-paper, #fdfcf9);border-bottom:1px solid #d7d0c5;flex:none}.kg-study-pages button{padding:7px 16px!important;border-radius:7px!important;font-size:13px}.kg-study-pages button[aria-pressed=true]{background:#f3e5dc;color:#803b28;font-weight:600}
.kg-study-shell .kg-classroom{height:auto!important;flex:1;overflow:hidden}.kg-study-content{background:var(--pwb-canvas, #f7f5f0)}.kg-study-shell .kg-classroom>aside{overflow:hidden;background:var(--pwb-paper, #fdfcf9)}.kg-study-shell nav[aria-label="学习角色"]{gap:6px!important;padding:10px!important;border-bottom:1px solid #e9e4db}.kg-study-shell nav[aria-label="学习角色"]>button{padding:6px 8px!important;border-radius:7px!important;font-size:12px}.kg-study-shell nav[aria-label="学习角色"]>button[aria-pressed=true]{background:#f3e5dc;color:#803b28}.kg-study-shell select,.kg-study-content input:not([type=checkbox]):not([type=radio]),.kg-study-content textarea{box-sizing:border-box;max-width:100%;min-width:0;min-height:38px!important;border:1px solid #cfc5b7!important;border-radius:8px!important;background:var(--pwb-paper, #fdfcf9);color:#2e2b26;font:inherit;font-size:13px;padding:8px 10px!important;transition:border-color .15s,box-shadow .15s}.kg-study-shell select{cursor:pointer;line-height:1.4}.kg-study-shell select:hover,.kg-study-content input:hover{border-color:#94a3b8!important}.kg-study-shell select:focus-visible,.kg-study-content input:focus-visible,.kg-study-content textarea:focus-visible{outline:none;border-color:#a44c32!important;box-shadow:0 0 0 3px #a44c3220}.kg-study-shell select:disabled{background:#f1f5f9;color:#94a3b8;cursor:not-allowed}.kg-study-shell nav select[aria-label="教师科目"]{flex:1 1 180px;width:100%;margin-top:2px}
.kg-study-shell .pwb-display-filter{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;padding:14px;background:var(--pwb-canvas, #f7f5f0);border:1px solid #ded7cd;border-radius:10px;margin:12px 0}.kg-study-shell .pwb-display-filter label{display:flex;flex-direction:column;gap:6px;font-size:12px;font-weight:500;color:#615a50;min-width:0}.kg-study-shell .pwb-display-filter label:first-child{grid-column:1/-1}.kg-study-shell .pwb-display-filter input,.kg-study-shell .pwb-display-filter select{width:100%}.kg-study-shell .pwb-display-list{list-style:none;margin:12px 0;padding:0;max-height:300px;overflow:auto;border:1px solid #ded7cd;border-radius:9px;background:var(--pwb-paper, #fdfcf9)}.kg-study-shell .pwb-display-list li{padding:10px 12px;border-bottom:1px solid #e9e4db;font-size:12px;color:#736c62}.kg-study-shell .pwb-display-list li:last-child{border-bottom:0}.kg-study-shell .pwb-display-list button{display:block!important;width:100%;padding:0!important;text-align:left;justify-content:flex-start!important;color:#2e2b26;line-height:1.6}.kg-study-shell .pwb-display-list li:has(button[aria-pressed=true]){background:#f3e5dc}.kg-study-shell .pwb-display-list button[aria-pressed=true]{color:#803b28;font-weight:600}
@media(max-width:760px){.kg-study-shell[data-study=true]{inset:0;border-radius:0}.kg-study-toolbar{padding:10px}.kg-study-toolbar span{display:none}.kg-study-pages{padding:6px 10px}.kg-study-shell nav[aria-label="学习角色"]{padding:6px!important}.kg-study-shell .pwb-display-filter{grid-template-columns:1fr}}
.kg-study-shell section[aria-label="持续角色会话"]>header summary{padding:5px 9px;border:1px solid var(--pwb-line);border-radius:6px;background:var(--pwb-paper);color:var(--pwb-muted)}
${controlStyles}
`
