/** Scoped styles: native DSH navigation and conversation controls keep their own theme. */
export const learningStyles = `
.kg-study-shell{display:flex;flex-direction:column;flex:1;min-width:0;min-height:0;height:100%;background:#f8fafc;outline:none}.kg-study-shell[hidden]{display:none}
.pwb-project:has(.kg-study-shell[data-study=true]:not([hidden]))>.pwb-pages,.pwb-project-shell:has(.kg-study-shell[data-study=true]:not([hidden]))>.pwb-top{visibility:hidden}
.kg-study-shell[data-study=true]{position:absolute;inset:12px;height:auto;z-index:5;border:1px solid #dbe2ea;border-radius:12px;box-shadow:0 12px 36px #172b4d24;overflow:hidden}
.kg-study-toolbar{display:flex;align-items:center;justify-content:space-between;gap:12px;flex:none;padding:12px 18px;background:#fff;border-bottom:1px solid #e5e7eb}.kg-study-toolbar>div{display:flex;flex-direction:column;gap:2px}.kg-study-toolbar strong{font-size:15px}.kg-study-toolbar span{font-size:12px;color:#64748b}.kg-study-toolbar button{display:inline-flex;align-items:center;gap:7px;padding:8px 12px!important;border:1px solid #dbe2ea!important;border-radius:8px!important;font-size:13px!important;white-space:nowrap}.kg-study-toolbar .kg-study-launch{background:#2563eb!important;color:white!important;border-color:#2563eb!important}
.kg-study-pages{display:flex;gap:6px;padding:8px 18px;background:#fff;border-bottom:1px solid #e5e7eb;flex:none}.kg-study-pages button{padding:7px 16px!important;border-radius:7px!important;font-size:13px}.kg-study-pages button[aria-pressed=true]{background:#eff6ff;color:#1d4ed8;font-weight:600}
.kg-study-shell .kg-classroom{height:auto!important;flex:1;overflow:hidden}.kg-study-content{background:#f8fafc}.kg-study-shell .kg-classroom>aside{overflow:hidden;background:#fff}.kg-study-shell nav[aria-label="学习角色"]{gap:6px!important;padding:10px!important;border-bottom:1px solid #eef2f6}.kg-study-shell nav[aria-label="学习角色"]>button{padding:6px 8px!important;border-radius:7px!important;font-size:12px}.kg-study-shell nav[aria-label="学习角色"]>button[aria-pressed=true]{background:#eff6ff;color:#1d4ed8}.kg-study-shell select,.kg-study-content input:not([type=checkbox]):not([type=radio]),.kg-study-content textarea{box-sizing:border-box;max-width:100%;min-width:0;min-height:38px!important;border:1px solid #cbd5e1!important;border-radius:8px!important;background:#fff;color:#1e293b;font:inherit;font-size:13px;padding:8px 10px!important;transition:border-color .15s,box-shadow .15s}.kg-study-shell select{cursor:pointer;line-height:1.4}.kg-study-shell select:hover,.kg-study-content input:hover{border-color:#94a3b8!important}.kg-study-shell select:focus-visible,.kg-study-content input:focus-visible,.kg-study-content textarea:focus-visible{outline:none;border-color:#2563eb!important;box-shadow:0 0 0 3px #2563eb20}.kg-study-shell select:disabled{background:#f1f5f9;color:#94a3b8;cursor:not-allowed}.kg-study-shell nav select[aria-label="教师科目"]{flex:1 1 180px;width:100%;margin-top:2px}
.kg-study-shell .pwb-display-filter{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;padding:14px;background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;margin:12px 0}.kg-study-shell .pwb-display-filter label{display:flex;flex-direction:column;gap:6px;font-size:12px;font-weight:500;color:#475569;min-width:0}.kg-study-shell .pwb-display-filter label:first-child{grid-column:1/-1}.kg-study-shell .pwb-display-filter input,.kg-study-shell .pwb-display-filter select{width:100%}.kg-study-shell .pwb-display-list{list-style:none;margin:12px 0;padding:0;max-height:300px;overflow:auto;border:1px solid #e2e8f0;border-radius:9px;background:#fff}.kg-study-shell .pwb-display-list li{padding:10px 12px;border-bottom:1px solid #eef2f6;font-size:12px;color:#64748b}.kg-study-shell .pwb-display-list li:last-child{border-bottom:0}.kg-study-shell .pwb-display-list button{display:block!important;width:100%;padding:0!important;text-align:left;justify-content:flex-start!important;color:#334155;line-height:1.6}.kg-study-shell .pwb-display-list li:has(button[aria-pressed=true]){background:#eff6ff}.kg-study-shell .pwb-display-list button[aria-pressed=true]{color:#1d4ed8;font-weight:600}
@media(max-width:760px){.kg-study-shell[data-study=true]{inset:0;border-radius:0}.kg-study-toolbar{padding:10px}.kg-study-toolbar span{display:none}.kg-study-pages{padding:6px 10px}.kg-study-shell nav[aria-label="学习角色"]{padding:6px!important}.kg-study-shell .pwb-display-filter{grid-template-columns:1fr}}
`
