import assert from 'node:assert/strict'
import {test} from 'node:test'
import React,{act} from 'react'
import {JSDOM} from 'jsdom'
import {RecipeEditor} from '../src/recipe-editor.tsx'
import {en,zh} from '../src/locale.ts'
const recipe={schemaVersion:1,appId:'app.generated',version:1,name:'Generated app',description:'Editable',pages:[{id:'home',label:'Home',layout:'grid',modules:[]}],connections:[],roles:[]}
test('requirements invoke generation only on explicit click, native cancel is sent, completed draft is editable and activation remains explicit',async()=>{
 const dom=new JSDOM('<div id="mount"></div>',{url:'http://localhost'}),original=new Map();for(const[name,value]of Object.entries({window:dom.window,document:dom.window.document,HTMLElement:dom.window.HTMLElement,IS_REACT_ACT_ENVIRONMENT:true})){original.set(name,Object.getOwnPropertyDescriptor(globalThis,name));Object.defineProperty(globalThis,name,{configurable:true,writable:true,value})}
 const oldFetch=globalThis.fetch,calls=[],opened=[];let count=0,records=[]
 globalThis.fetch=async(url,options)=>{const request=JSON.parse(options.body);calls.push({url,...request});let value;if(url.endsWith('/generation')){if(request.action==='start'){count++;if(count===1)value={job:{id:'first',appId:request.appId,status:'running'}};else {const record={appId:request.appId,revision:1,draft:{...recipe,appId:request.appId}};records=[record];value={job:{id:'second',appId:request.appId,status:'completed',sessionId:'native-session',record}}}}else value={job:{id:request.id,appId:'app.generated',status:'cancelled',error:'Generation cancelled'}}}else if(request.action==='workspaces')value={workspaces:['/trusted/one','/trusted/two']};else if(request.action==='catalog')value={recipes:records};else if(request.action==='save'){records=[{...records[0],revision:records[0].revision+1,draft:request.recipe}];value={record:records[0]}}else if(request.action==='preview')value={recipe:records[0].draft};else value={record:records[0]};return{ok:true,json:async()=>value}}
 const {createRoot}=await import('react-dom/client'),root=createRoot(document.getElementById('mount'));const click=async text=>{const button=[...document.querySelectorAll('button')].find(b=>b.textContent===text);assert.ok(button,text);await act(async()=>button.click())}
 try{await act(async()=>root.render(React.createElement(RecipeEditor,{t:k=>en[k]??k,refresh:async()=>{},onOpenSession:id=>opened.push(id)})));assert.equal(calls.some(c=>c.action==='start'),false)
 const input=document.querySelector('textarea[aria-label="Application requirements"]');await act(async()=>{Object.getOwnPropertyDescriptor(dom.window.HTMLTextAreaElement.prototype,'value').set.call(input,'Build my dashboard');input.dispatchEvent(new dom.window.Event('input',{bubbles:true}))});assert.equal(calls.some(c=>c.action==='start'),false)
 const workspace=document.querySelector('select[aria-label="Application workspace"]');assert.ok(workspace,'AI generation exposes its target workspace');await act(async()=>{Object.getOwnPropertyDescriptor(dom.window.HTMLSelectElement.prototype,'value').set.call(workspace,'/trusted/two');workspace.dispatchEvent(new dom.window.Event('change',{bubbles:true}))});
 await click(en.generationStart);assert.equal(calls.find(c=>c.action==='start').workspace,'/trusted/two');await click(en.generationCancel);assert.equal(calls.filter(c=>c.action==='cancel').length,1);assert.match(document.body.textContent,/Generation cancelled/)
 await click(en.generationStart);assert.equal(document.querySelector('input[aria-label="'+en.recipeName+'"]').value,'Generated app');assert.equal(calls.some(c=>c.action==='activate'),false);const name=document.querySelector('input[aria-label="'+en.recipeName+'"]');await act(async()=>{Object.getOwnPropertyDescriptor(dom.window.HTMLInputElement.prototype,'value').set.call(name,'Edited generated app');name.dispatchEvent(new dom.window.Event('input',{bubbles:true}))});await click(en.recipeSave);assert.equal(calls.find(c=>c.action==='save').recipe.name,'Edited generated app');await click(en.generationOpenSession);assert.deepEqual(opened,['native-session']);assert.ok(document.querySelector('[aria-label="'+en.canvasTitle+'"]'));await click(en.recipePreview);assert.equal(calls.some(c=>c.action==='activate'),false);await click(en.recipeActivate);assert.equal(calls.filter(c=>c.action==='activate').length,1)
 for(const key of Object.keys(en).filter(k=>k.startsWith('generation'))){assert.ok(zh[key],key);assert.notEqual(zh[key],en[key],key)}
 }finally{await act(async()=>root.unmount());dom.window.close();globalThis.fetch=oldFetch;for(const[name,value]of original){if(value)Object.defineProperty(globalThis,name,value);else delete globalThis[name]}}
})
