import {scopedConversation} from './scoped-conversation-fixture.mjs'
import assert from 'node:assert/strict'
import {test} from 'node:test'
import React,{act} from 'react'
import {JSDOM} from 'jsdom'
import {readFile} from 'node:fs/promises'
import {createRequire} from 'node:module'
import {runInNewContext} from 'node:vm'
const require=createRequire(import.meta.url)
test('built display modules capture current selected/filter/aggregate data per instance and send only edited remaining context once',async()=>{
 const dom=new JSDOM('<div id="mount"></div>',{url:'http://localhost'}),original=new Map()
 for(const[name,value]of Object.entries({window:dom.window,document:dom.window.document,HTMLElement:dom.window.HTMLElement,IS_REACT_ACT_ENVIRONMENT:true})){original.set(name,Object.getOwnPropertyDescriptor(globalThis,name));Object.defineProperty(globalThis,name,{configurable:true,writable:true,value})}
 const services={},cleanups=[],requests=[],sent=[];let api
 const fetch=async(url,options)=>{const data=JSON.parse(options.body);requests.push({url,...data});if(url.endsWith('/recipes'))return{ok:true,json:async()=>({version:1,recipes:[]})};if(url.endsWith('/apps'))return{ok:true,json:async()=>({version:1,states:[]})};assert.ok(url.endsWith('/roles'));return{ok:true,json:async()=>({binding:data.action==='read'?null:{version:1,key:data.key,sessionId:data.key.instanceId+'-analyst',presetId:'p',phase:'ready',previousSessionIds:[]}})}}
 const window=Object.assign(dom.window,{__ModuleLoader__:{load:({factory})=>api=factory(require)}})
 await runInNewContext(await readFile(new URL('../lib/client.js',import.meta.url),'utf8'),{window,console,AbortController,fetch,structuredClone})
 const ctx={get:name=>services[name],effect:run=>{const cleanup=run();if(typeof cleanup==='function')cleanups.push(cleanup);return cleanup},inject:(names,run)=>{if(names.includes('uiConversation')||names.includes('conversation')||names.includes('personalWorkbenchRoles'))run(ctx)},reflect:{provide:(name,value)=>{services[name]=value;ctx[name]=value;return()=>{delete services[name]}}},locale:{register:()=>()=>{}},conversation:{send:()=>assert.fail('Ambient send')},workspaces:{list:{getSnapshot:()=>({phase:'ready',state:'idle',archivedSessionIds:[]}),subscribe:()=>()=>{}}},sessions:{retain:id=>({sessionId:id,binding:{session:{getSnapshot:()=>({openState:'open',removed:false}),subscribe:()=>()=>{}},ctx:scopedConversation(async text=>sent.push({id,text}))},ready:Promise.resolve(),release:()=>{}}),async using(id,_options,run){const ref=this.retain(id);try{return await run(ref)}finally{ref.release()}}},slots:{inject:(_name,run)=>{const cleanup=run();if(typeof cleanup==='function')cleanups.push(cleanup)},register:()=>()=>{},registerFactory:()=>()=>{}}}
 api.apply(ctx)
 const removeSource=api.registerDisplaySource({appId:'reading',resource:'books',label:'Owned books',load:async({instanceId})=>({records:[{id:'a',title:instanceId+' A',fields:{category:'x',pages:10}},{id:'b',title:instanceId+' B',fields:{category:'y',pages:20}}],filters:[{field:'category',label:'Category'}],stats:[{id:'count',label:'Count',operation:'count'},{id:'pages',label:'Pages',operation:'sum',field:'pages'}]})})
 const modules=['filter','stats','list','detail'].map(type=>({id:type,type,title:type,connectionId:'books',...(type==='list'||type==='stats'?{roleId:'analyst'}:{}),config:{taskPrompt:'Analyze selected books'}}))
 const recipe={schemaVersion:1,appId:'reading',version:1,name:'Reading',description:'',connections:[{id:'books',sourceAppId:'reading',resource:'books'}],roles:[{id:'analyst',name:'Analyst',presetId:'p',skillNames:[]}],pages:[{id:'home',label:'Home',layout:'stack',modules},{id:'other',label:'Other',layout:'stack',modules:modules.map(m=>({...m,id:'other.'+m.id}))}]}
 const {createRoot}=await import('react-dom/client'),root=createRoot(document.getElementById('mount'))
 const key=instanceId=>({appId:'reading',instanceId,roleId:'analyst'}),tasks=services.personalWorkbenchTasks,prepared=instance=>tasks.getSnapshot().get(JSON.stringify(['reading',instance,'analyst',null])).prepared
 const render=(instanceId,pageId='home')=>root.render(React.createElement(api.RecipePage,{recipe,pageId,appId:'reading',instanceId,ctx,t:k=>k}))
 const click=async text=>{const button=[...document.querySelectorAll('button')].find(b=>b.textContent===text);assert.ok(button,text);await act(async()=>button.click())}
 const prepare=async type=>{const section=[...document.querySelectorAll('h3')].find(h=>h.textContent===type).closest('.pwb-recipe-module');const button=[...section.querySelectorAll('button')].find(b=>b.textContent==='taskPrepared');assert.ok(button);await act(async()=>button.click())}
 const parsedChunk=(instance,suffix)=>JSON.parse(prepared(instance).context.find(c=>c.id.endsWith('.'+suffix)).text)
 try {
  await act(async()=>render('first'));await click('first A');await prepare('list');assert.equal(parsedChunk('first','selection').title,'first A');await click('first B');assert.equal(parsedChunk('first','selection').title,'first A','Prepared evidence is a frozen snapshot');await prepare('list');assert.equal(parsedChunk('first','selection').title,'first B')
  await act(async()=>{const select=document.querySelector('select[aria-label="Category"]');select.value='x';select.dispatchEvent(new dom.window.Event('change',{bubbles:true}))});await click('first A');await prepare('stats');assert.deepEqual(parsedChunk('first','scope').filters,{category:'x'});assert.equal(parsedChunk('first','statistics').statistics.find(s=>s.id==='count').value,1);assert.equal(parsedChunk('first','statistics').statistics.find(s=>s.id==='pages').value,10)
  await act(async()=>render('second'));await click('second B');await prepare('list');assert.equal(parsedChunk('second','selection').title,'second B');assert.equal(parsedChunk('first','selection').title,'first A');assert.equal(parsedChunk('second','scope').search,'');assert.deepEqual(parsedChunk('second','scope').filters,{})
  await act(async()=>render('first','other'));assert.equal(document.querySelector('select[aria-label="Category"]').value,'x');await prepare('list');assert.equal(parsedChunk('first','selection').title,'first A');assert.deepEqual(parsedChunk('first','scope').filters,{category:'x'});assert.equal(requests.filter(r=>r.action==='ensure').length,0);assert.deepEqual(sent,[])
  const pending=prepared('first');await act(async()=>{tasks.editTask(key('first'),'Edited task');tasks.editContext(key('first'),pending.context.find(c=>c.id.endsWith('.selection')).id,'User edited book context');tasks.removeContext(key('first'),pending.context.find(c=>c.id.endsWith('.scope')).id)});const textareas=[...document.querySelectorAll('textarea')];assert.ok(textareas.some(t=>t.value==='User edited book context'));assert.ok(!textareas.some(t=>t.value.includes('matchedRecords')));await click('taskSend');assert.deepEqual(sent.map(s=>s.id),['first-analyst']);assert.ok(sent[0].text.startsWith('Edited task'));assert.ok(sent[0].text.includes('User edited book context'));assert.ok(!sent[0].text.includes('first A'));assert.ok(!sent[0].text.includes('second B'));assert.equal(requests.filter(r=>r.action==='ensure').length,1)
  await act(async()=>removeSource());await prepare('list');assert.match(document.body.textContent,/displayUnavailable/);assert.equal(tasks.getSnapshot().has(JSON.stringify(['reading','first','analyst',null])),false);assert.equal(sent.length,1)
 } finally {await act(async()=>root.unmount());removeSource();for(const cleanup of cleanups.reverse())cleanup();dom.window.close();for(const[name,value]of original){if(value)Object.defineProperty(globalThis,name,value);else delete globalThis[name]}}
})
